[package]
name = "rotohash-rs"
version = "0.1.2"
edition = "2024"
rust-version = "1.89"
description = "Hashing for High-Bandwidth (>100 GiB/sec) Data"
license = "MIT"
repository = "https://github.com/int08h/rotohash-rs"
keywords = ["hash", "checksum", "simd", "avx2", "neon"]
categories = ["algorithms"]
exclude = ["benches", "examples", "tests"]

[lib]
name = "rotohash"

[[bench]]
name = "performance"
harness = false

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
